import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Header from '../components/header/header';
import BannerImage from '../public/assets/images/landing-slide.jpg'; 
import ListItems from '../components/ListItems/listItems';
import { List } from '../utils/listItem';
import Footer from '../components/footer/footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles.bannerImages}>
          <Image src={BannerImage}  alt='Banner Image' />
          <div className={styles.bannerText}>
            <h2>
              <span className={styles.bannerMainHeading}>The Shop Theme You have Been Waiting For.</span>
            </h2>
            <div>
              <h3>
                <span className={styles.bannerSubHeading}>Suprema is a powerful multipurpose theme for eCommerce that lets you quickly set up and launch an awesome online shop.</span>
              </h3>
            </div>
            <div>
              <button className={styles.bannerBtn}>View Home Pages</button>
            </div>
          </div>
        </div>
        <div className={styles.content}>
        {
          List && List.length > 0 && List.map(items => <ListItems key={items.id} listData={items} />)
        }
        </div>
      </main>

        <Footer />
    </div>
  )
}

// export const getStaticProps = async () => {
//   const res = await fetch('https://fakestoreapi.com/products');
//   const data = await res.json();
//   debugger;
//   return  {
//     props: {
//       data
//     },
//   }
// }